FROM golang:1.17

COPY ./wallet-service /go/src/github.com/roozbehrahmani/abrarvan_test
WORKDIR /go/src/github.com/roozbehrahmani/abrarvan_test
ENV BIN=/go/src/github.com/roozbehrahmani/abrarvan_test/bin
ENV GOBIN=/go/src/github.com/roozbehrahmani/abrarvan_test/bin
# RUN go mod tidy

RUN go mod vendor
RUN go install -mod=vendor -v -ldflags "-s" ./cmd/seed/...

CMD ["/go/src/github.com/roozbehrahmani/abrarvan_test/bin/seed"]

