version: '3.8'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@SSWORD
      - MYSQL_DATABASE=arvancloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=golang
      - MYSQL_PASSWORD=password
    networks:
      arvancloud:
        ipv4_address: 172.31.1.2
    volumes:
      - my-db:/var/lib/mysql
  discount:
    build:
      context: ..
      dockerfile: discount-service/deploy/Dockerfile
    ports:
      - '8080:8080'
    links:
      - database
    depends_on:
      - database
    container_name: arvancloud-discount-container
    networks:
      arvancloud:
        ipv4_address: 172.31.1.3
  wallet:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - database
      - discount
    links:
      - database
      - discount
    container_name: arvancloud-wallet-container
    networks:
      arvancloud:
        ipv4_address: 172.31.1.4

volumes:
  my-db:
  database:
    driver: local



networks:
  arvancloud:
    name: arvancloud-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/24



