version: '3.8'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=arvancloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - arvancloud
  wallet:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - database
    links:
      - database
    container_name: arvancloud-wallet-container
    networks:
      - arvancloud
  discount:
    build:
      context: ..
      dockerfile: discount-service/deploy/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    container_name: arvancloud-discount-container
    networks:
      - arvancloud

volumes:
  my-db:
  database:
    driver: local



networks:
  arvancloud:
    name: arvancloud-network
    driver: bridge



