version: '3.8'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@SSWORD
      - MYSQL_DATABASE=arvancloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=golang
      - MYSQL_PASSWORD=password
    networks:
      - arvancloud
    volumes:
      - my-db:/var/lib/mysql
  discount:
    build:
      context: ..
      dockerfile: discount-service/deploy/Dockerfile
    ports:
      - '8080:8080'
    links:
      - database
    depends_on:
      - database
    container_name: arvancloud-discount-container
    networks:
      - arvancloud

  wallet:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - database
      - discount
    links:
      - database
      - discount
    container_name: arvancloud-wallet-container
    networks:
      - arvancloud

volumes:
  my-db:
  database:
    driver: local



networks:
  arvancloud:
    name: arvancloud-network
    driver: bridge



