version: '3.8'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=arvancloud
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - arvancloud
  migrate:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile-migrate

  seed:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile-seed


volumes:
  my-db:
  database:
    driver: local



networks:
  arvancloud:
    name: arvancloud-network
    driver: bridge