version: '3.8'
services:
  database:
    image: mysql:5.7
    restart: always
    container_name: arvancloud-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=arvancloud
    ports:
      - "3307:3306"
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
  wallet:
    build:
      context: ..
      dockerfile: wallet-service/deploy/Dockerfile
    ports:
      - '8081:8081'
    links:
      - database
    container_name: arvancloud-wallet-container
  discount:
    build:
      context: ..
      dockerfile: discount-service/deploy/Dockerfile
    ports:
      - '8080:8080'
    links:
      - database
    container_name: arvancloud-discount-container

#    links:
#      - cache
volumes:
  my-db:
  database:
    driver: local


